name: ingre-scan
channels:
  - anaconda
  - fastai
  - pytorch
  - defaults
dependencies:
  - boto3
  - pandas==1.1.5
  - fastai==1.0.61
  - torchvision==0.11.1
  - scikit-learn==1.0.1
  - flask==2.0.2
  - flask-sqlalchemy==2.5.1
  - werkzeug==2.0.2
  - pymysql
